/arm2d2/controllers:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  velocity:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
    gains:
      joint_1: {p: 5,  d: 0.1, i: 0.5, i_clamp: 1}
      joint_2: {p: 40,  d: 0.1, i: 1, i_clamp: 1}
      joint_3: {p: 40,  d: 0.1, i: 2, i_clamp: 1}
      joint_4: {p: 10,  d: 0.1, i: 1, i_clamp: 1}
      joint_5: {p: 10,  d: 0.1, i: 1, i_clamp: 1}


  position:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

    constraints:
      goal_time: 0.1
      joint_1:
          trajectory: 0.2
          goal: 0.1
      joint_2:
          trajectory: 0.2
          goal: 0.1
      joint_3:
          trajectory: 0.2
          goal: 0.1
      joint_4:
          trajectory: 0.2
          goal: 0.1
      joint_5:
          trajectory: 0.2
          goal: 0.1