/arm2d2/controllers:
  state:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  velocity:
    type: "velocity_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - gripper_joint
    gains:
      joint_1: {p: 2,  d: 0.1, i: 0.005, i_clamp: 1}
      joint_2: {p: 30,  d: 0, i: 0.1, i_clamp: 1}
      joint_3: {p: 30,  d: 0, i: 0.1, i_clamp: 1}
      joint_4: {p: 8,  d: 0, i: 0.1, i_clamp: 1}
      joint_5: {p: 8,  d: 0, i: 0.01, i_clamp: 1}
      gripper_joint: {p: 1, d: 0, i: 0.01, i_clamp: 1}


  position:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

    constraints:
      goal_time: 0.1
      joint_1:
          trajectory: 0.2
          goal: 0.1
      joint_2:
          trajectory: 0.2
          goal: 0.1
      joint_3:
          trajectory: 0.2
          goal: 0.1
      joint_4:
          trajectory: 0.2
          goal: 0.1
      joint_5:
          trajectory: 0.2
          goal: 0.1